"""Demand-aware topology and common capacity optimization contracts."""

from .capacity import (
    CAPACITY_INITIALIZER_VERSION,
    CAPACITY_OBJECTIVE_VERSION,
    CAPACITY_SEARCH_VERSION,
    CapacityObjectiveScore,
    CapacityOptimizationManifest,
    CapacityOptimizationPlan,
    CapacityOptimizationResult,
    CapacityOptimizationStep,
    CapacityProposalEvaluation,
    CapacityScenarioOutcome,
    CapacityTrainingScenario,
    initialize_load_risk_state,
    optimize_common_capacity,
    score_capacity_state,
    validate_capacity_state,
    validate_common_capacity_result,
)
from .constructor import (
    CANDIDATE_GENERATOR_VERSION,
    EXHAUSTIVE_CANDIDATE_NODE_LIMIT,
    TOPOLOGY_SEARCH_VERSION,
    ConnectedCandidate,
    ConnectedCandidatePool,
    DemandAwareSearchPlan,
    DemandAwareSearchStep,
    DemandAwareTopologyResult,
    generate_connected_candidate_pool,
    train_demand_aware_topology,
    validate_connected_candidate_pool,
    validate_demand_aware_topology_result,
)

from .demand import (
    DEMAND_OBJECTIVE_VERSION,
    DemandAwareObjectiveScore,
    DemandAwareObjectiveWeights,
    DemandAwareTrainingManifest,
    DirectedDemandMatrix,
    OptimizationError,
    score_demand_aware_topology,
    validate_demand_aware_score,
    validate_demand_aware_topology,
)


__all__ = [
    "CAPACITY_INITIALIZER_VERSION",
    "CAPACITY_OBJECTIVE_VERSION",
    "CAPACITY_SEARCH_VERSION",
    "CANDIDATE_GENERATOR_VERSION",
    "DEMAND_OBJECTIVE_VERSION",
    "EXHAUSTIVE_CANDIDATE_NODE_LIMIT",
    "TOPOLOGY_SEARCH_VERSION",
    "ConnectedCandidate",
    "ConnectedCandidatePool",
    "CapacityObjectiveScore",
    "CapacityOptimizationManifest",
    "CapacityOptimizationPlan",
    "CapacityOptimizationResult",
    "CapacityOptimizationStep",
    "CapacityProposalEvaluation",
    "CapacityScenarioOutcome",
    "CapacityTrainingScenario",
    "DemandAwareObjectiveScore",
    "DemandAwareObjectiveWeights",
    "DemandAwareSearchPlan",
    "DemandAwareSearchStep",
    "DemandAwareTopologyResult",
    "DemandAwareTrainingManifest",
    "DirectedDemandMatrix",
    "OptimizationError",
    "generate_connected_candidate_pool",
    "initialize_load_risk_state",
    "optimize_common_capacity",
    "score_capacity_state",
    "score_demand_aware_topology",
    "train_demand_aware_topology",
    "validate_connected_candidate_pool",
    "validate_capacity_state",
    "validate_common_capacity_result",
    "validate_demand_aware_score",
    "validate_demand_aware_topology",
    "validate_demand_aware_topology_result",
]
